# Generated by Django 3.0.3 on 2021-02-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbook', '0002_auto_20210201_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile.png', upload_to='profile_pics'),
        ),
    ]
