# Generated by Django 3.0.3 on 2021-02-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbook', '0003_auto_20210201_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
