# Generated by Django 3.0.3 on 2021-02-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbook', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, '新品、未使用'), (2, '未使用に近い'), (3, '目立った傷や汚れなし'), (4, 'やや傷や汚れあり'), (5, '傷や汚れあり'), (6, '全体的に状態が悪い')], default=1, verbose_name='商品の状態'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=5000, verbose_name='一言'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_pics', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
